apiVersion: v1
kind: Service
metadata:
  name: inventario-service-bg
spec:
  type: NodePort
  selector:
    app: inventario-app
    version: green   # <--- AQUÍ CAMBIAS A "green" PARA HACER EL CORTE DE TRÁFICO 
  ports:
  - port: 3000
    targetPort: 3000